// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/config"
	"server/configs"
	"strconv"
)

func main() {
	h := server.New(config.Option{F: func(o *config.Options) {
		o.Addr = ":" + strconv.Itoa(configs.Get().HttpPort)
	}})
	customizedRegister(h)
	h.Spin()
}
