// Code generated by hertz generator.

package main

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"server/common/middleware"
	"server/configs"
	"server/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/health", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(consts.StatusOK, utils.H{"message": "pong"})
	})

	apiGroup := r.Group("/api")
	r.Use(middleware.InnerAuth(configs.Get().InnerPrivateKey))

	// 用户登录 + 退出登录 + 密码修改
	apiGroup.POST("/login", handler.DrugList)
	apiGroup.POST("/login-out", handler.DrugList)
	apiGroup.POST("/modify-pwd", handler.DrugList)

	// 查询所有基础药品 名称 + 状态 搜索 (id倒序 + 分页)
	apiGroup.POST("/drug-list", handler.DrugList)

	// 药品添加 名称
	apiGroup.POST("/drug-add", handler.DrugList)

	// 药品状态修改 状态修改
	apiGroup.POST("/drug-status", handler.DrugList)

	// 查询所有竞品商家 暂不支持添加
	apiGroup.POST("/shop-list", handler.DrugList)

	// 药品价格查询 输入药品名字 + 商家搜索
	apiGroup.POST("/drug-price", handler.DrugList)

	// 药品价格导出
	apiGroup.POST("/drug-price", handler.DrugList)

	// 抓取记录
	// apiGroup.POST("/grab-list", handler.DrugList)

	// 统计接口 药品总数 商家总数 抓取次数 成功次数
	apiGroup.POST("/stat", handler.DrugList)

	// 系统自动抓取程序
}



# 登录页面
# 首页 接指标数据 显示就可以了
# 药品管理
# 商家管理
# 价格查询

