// Code generated by hertz generator.

package handler

import (
	"codeup.aliyun.com/616ff38165b9775dd591fcc9/jgj-common/rpc/service/jz-middle-end/userrightscenter"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"server/common"
)

// DrugList .
// @router /drug-list [POST]
func DrugList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userrightscenter.GetUserBeanReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userrightscenter.GetUserBeanResp)
	resp.Data = &userrightscenter.GetUserBeanRespData{}
	// beanLogic := logic.NewGetUserBeanLogic(req.Uid)
	// beanResult, err := beanLogic.Get()
	if err != nil {
		resp.Code = common.FAIL
		resp.Desc = err.Error()
	} else {
		resp.Code = common.SUCCESS
	}

	c.JSON(consts.StatusOK, resp)
}
